AWSTemplateFormatVersion: 2010-09-09
Metadata: 
   Licence: if any mention here
Description: ec2 + security group + Key pair 
Parameters: 
    KeyName: 
       Description: Enter keypair for ec2 instance 
       Type: AWS::EC2::KeyPair::KeyName
       #AllowedValues: 
       ConstraintDescription: Give an existing keyPair
    InstanceType:
       Description: EC2 instance type
       Type: String
       Default: t2.micro
       AllowedValues: [t2.micro,t2.nano,t2.small,t3.micro,t3.nano,t3.small]
       ConstraintDescription: Only free-tier instances
    SSHLocation: 
       Description: IP address range to allow through security group port 22
       Type: String
       MinLength: 8
       MaxLength: 18
       Default: 0.0.0.0/0
       AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,3})
       ConstraintDescription: IP CIDR Range in form x.x.x.x/x
    AMIid: 
       Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
       Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
Resources:
    EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        KeyName: !Ref KeyName
        DisableApiTermination: false
        ImageId: !Ref AMIid
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        UserData: !Base64 |
          !/bin/bash -ex
          yum update -y
        Tags:
          - Key: Name
            Value: CF-created-instance
    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        GroupDescription: ENables SSH via port 22
        SecurityGroupIngress: 
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
Outputs:
    InstanceId:
      Description: IntanceId of newly created ec2 
      Value: !Ref EC2Instance
    AZ:
      Description: Availability zone of newly created ec2
      Value: !GetAtt [EC2Instance,AvailabilityZone]
    PublicDNS:
      Description: Public DNS name of ec2
      Value: !GetAtt [EC2Instance,PublicDnsName]
    PublicIP:
      Description: Public IP of newly created ec2
      Value: !GetAtt [EC2Instance,PublicIp]
    PrivateIP:
      Description: Private IP of newly created ec2
      Value: !GetAtt [EC2Instance,PrivateIp]